### ISSUE TITLE
todo example: bugs and not comply to the standard template

### ISSUE THREAD

**Issue by aclueless** [ivanceras/sauron#14]
Testing the demo at: https://ivanceras.github.io/todomvc/

* Bugs:
1. Create 2 todo items
2. Double click the first item
3. Double click the second item => The first item should be un-edit
4. Click back to the first item,
5. Click the second item => error unreachable in console

* Not comply to the standard (just saw on demo, I did not read the code)
1. Not implement persistent storage
2. Number of "item left" not update when check/uncheck an item
3. "Clear complete" not hidden when there is no item checked

I saw you update sauron on https://github.com/schell/todo-mvc-bench/pull/44 and I think frameworks should implement standard features to compare.

**Comment by ivanceras** [comment]
Hi @aclueless thanks for opening the issue, I didn't realize that the todo-mvc has a lot behavior that doesn't comply with the standard. I'll have to redo the todomvc and consider the bugs and features needed to be in there.

**Comment by ivanceras** [comment]
This has been fixed in 0.32.0
