### ISSUE TITLE
Web component support

### ISSUE THREAD

**Issue by damodharanj** [ivanceras/sauron#16]
Is it possible to compile to web component target ? Also how can we use existing web components ?
https://www.webcomponents.org/
This is really cool & want to try it out for an hustle that is in web components using lit-html

**Comment by ivanceras** [comment]
Web components looks cool, but I think it is suited for small widgets that can be slapped together in a webapp. I don't think using sauron would be a good candidate for that since the size of the compiled wasm binary is around ~500KB
