### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by Hau-Hau** [ivanceras/sauron#17]
Hello, I saw reddit post that announce production ready version of sauron framework. 
On production and real world business applications support of IE11 is unfortunately must have. 
Is sauron supports IE11 or have this feature in plans?

**Comment by ivanceras** [comment]
Unfortunately, supporting ie11 will not be a priority right now, as there are some bugs even in the latest versions of chrome, firefox, brave and edge. And also it needs to run a browser with support for web assembly, and ie11 don't have that. So it will require compiling wasm to js to run in older browsers.
