### ISSUE TITLE
README.md's Cargo.toml missing wasm-bindgen dependency?

### ISSUE THREAD

**Issue by Ran4** [ivanceras/sauron#19]
I followed the examples in README.md, but `wasm-pack build --target no-modules` fails:

```rust
Compiling saurontest v0.1.0 (/home/ran/src/rust/sauron/saurontest)
error: cannot find attribute `wasm_bindgen` in this scope
 --> src/lib.rs:21:3
    |
    21 | #[wasm_bindgen(start)]
       |   }}}}}}}}}}}}

       error: aborting due to previous error
```
This can be fixed by:

1. Adding `wasm-bindgen = "0.2"` to dependencies
2. Adding `use wasm_bindgen::prelude::*;` or similar to the src/lib.rs file

As a beginner wasm developer, I think it would be nice if the readme would explicitly say that the main code should go in `src/lib.rs` and not `src/main.rs` (Currently the `index.html` contents are prefixed with `index.html`, the lib.rs code could also be prefixed with `src/lib.rs`) :)

And perhaps mentioning Sauron requiring nightly.

**Comment by ivanceras** [comment]
The `wasm-bindgen` is reexported in sauron and you can import it with `use sauron::prelude::*;` .
Please take a look at the `minimal` example in the [examples](https://github.com/ivanceras/sauron/tree/master/examples) directory.
There is also a comprehensive `scripts` inside of each project example which shows you how to build the projects depending on profile.

The latest version of `sauron` does not requires the nightly compiler anymore as of version `0.28.0`
Documentation is still rough at the moment.

**Comment by Ran4** [comment]
>The wasm-bindgen is reexported in sauron and you can import it with use sauron::prelude::*; .
>The latest version of sauron does not requires the nightly compiler anymore as of version 0.28.0

You're absolutely right - I was using stable rust, but a few months out of date. It compiles just fine on stable rust 1.45.2, sorry!
As a side effect the sauron prelude import did not work (no idea why).
