### ISSUE TITLE
Examples don't rub in Safari because wasm_bindgen is undefined

### ISSUE THREAD

**Issue by gbj** [ivanceras/sauron#20]
Running one of the examples in Safari leads to an immediate `ReferenceError: Can't find variable: wasm_bindgen` in the console. If you then immediately type `wasm_bindgen` into the console REPL, it's defined. You can then copy and paste the loading code `wasm_bindgen('pkg/futuristic_ui_bg.wasm').catch(console.error);` and the app runs perfectly.

My guess is that Safari is async loading the first `script` (which defines `wasm_bindgen`) and running the second `script` (which calls it) before the first one is parsed.

The solution may be to do a dynamic `import(...).then(...)` chain.

**Comment by ivanceras** [comment]
Thanks for filing an issue @gbj I will resolve this issue soon as I'm on a mac.

**Comment by ivanceras** [comment]
The fix would be to build in `wasm-pack` with `web` as the target instead of `no-modules` as all the other examples are using.
```sh
wasm-pack build --target web
```
in the `index.html`, use the `import` and wrap it in a `async` function which calls on an await for loading the `wasm`. 
```javascript
<script type=module>
      import wasm_bindgen from './pkg/futuristic_ui.js';
      async function start(){
        await wasm_bindgen().catch(console.error);
      }
      start();
</script>
```

**Comment by gbj** [comment]
This runs on Safari. Thanks!
