### ISSUE TITLE
Want an example of server-side rendering?

### ISSUE THREAD

**Issue by gbj** [ivanceras/sauron#22]
I was messing around this afternoon and managed to put together a working setup to render my app in Warp including pre-populating it with API data, and then passing app state in on the client-side. I’d be happy to share a repo with a minimal reproduction if you want it, to use as an example. 

I have loved working with Sauron. Thanks for creating it!

**Comment by ivanceras** [comment]
Yes please! Thank you for using sauron @gbj

**Comment by ivanceras** [comment]
There has been a lot of revert and re-merged, but I was able to make it without having to resort on `git push --force`

Thank you @gbj for this server-side example. It's very clean and concise.
