### ISSUE TITLE
Benchmarks are misleading and need to be updated.

### ISSUE THREAD

**Issue by awulkan** [ivanceras/sauron#27]
I'm sure that Sauron is fast, but I think the benchmarks are highly misleading. For example, the Vue version (0.10) used in "benchmark 2" is from 2014. I think it's very important to not misrepresent other frameworks if performance is one of the main selling points of Sauron.

**Comment by pickfire** [comment]
I would be interested to see a comparison with vue 3 release too.

**Comment by ivanceras** [comment]
I had been trying out https://github.com/krausest/js-framework-benchmark but it seems to always fail when I try to build and run it. I made sure that node and npm version are up-to-date, but the error still persist.

I guess it's just me, but my gripes of node base projects like this is that everytime I try to checkout and build there will always be issues and errors, but the error logs are not helping as well.

There is one benchmark from mogwai project https://github.com/schell/todo-mvc-bench/ which just works right out.
