### ISSUE TITLE
node!(<h1>"example"</h1>) syntax does not work on released version 0.32.4

### ISSUE THREAD

**Issue by sesh22** [ivanceras/sauron#28]
Compiling the [minimal macro syntax example](https://github.com/ivanceras/sauron/tree/master/examples/minimal-macro-syntax) fails if `Cargo.toml` has `sauron = "0.32.4"`, but succeeds when using the relative path (`sauron = { path = "../../"}`) or the tagged version directly from Git (`sauron = { git = "https://github.com/ivanceras/sauron", tag = "0.32.4" }`).

Build error:

```rust
node! {
    <main>
        <h1>"Minimal example"</h1>
        <div class="some-class" id="some-id" {attr("data-id", 1)}>

    </main>
}
^ expected struct `sauron::Text`, found struct `std::string::String`
```

I narrowed this down to the string literal in the `h1` tag: `node!(<h1>"example"</h1>)`.
Using the full `node!(<h1>{text("example")}</h1>)` works with no problem.

I haven't been able to find a root cause, but I think it has to do with the latest `sauron-node-macro` version (0.32.0) being released before the fixes in e27c30bc2296a4c139adcb11bdd8a88f61b33f8f. If this is true then releasing a new version with bumped versions should resolve the problem.

**Comment by ivanceras** [comment]
@sesh22 thank you for reporting, I was able to reproduce the error.

**Comment by ivanceras** [comment]
@sesh22 I bump up [`sauron-node-macro`](https://crates.io/crates/sauron-node-macro) and it fixed the minimal example using the node macro syntax. Thank you for catching this error.

**Comment by sesh22** [comment]
@ivanceras Thanks! After running `cargo update` on my project `sauron = "0.32.4"` works again.
