### ISSUE TITLE
Error: Window is not defined [Cloudflare Worker]

### ISSUE THREAD

**Issue by deboboy** [ivanceras/sauron#29]
Getting this error after publishing your first example to a Cloudflare Worker:

[2021-01-01 17:07:25] GET example.com/ HTTP/1.1 500 Internal Server Error
Uncaught (in promise)
ReferenceError: Window is not defined
    at imports.wbg.__wbg_instanceof_Window_747b56d25bab9510 (worker.js:314:46)
    at <anonymous>:wasm-function[554]:0x2300e
    at <anonymous>:wasm-function[464]:0x21bf1
    at <anonymous>:wasm-function[510]:0x22827
    at <anonymous>:wasm-function[432]:0x21143
    at <anonymous>:wasm-function[433]:0x21199
    at <anonymous>:wasm-function[448]:0x216bd
    at <anonymous>:wasm-function[421]:0x20dad
    at main (<anonymous>:wasm-function[701]:0x23dff)
    at init (worker.js:531:10)
Uncaught (in response)
ReferenceError: Window is not defined

**Comment by ivanceras** [comment]
It seems like you are trying to run the wasm code in a web worker, which has no access to the DOM, hence it could not find the Window object.
