### ISSUE TITLE
Interval / timeout / any way to execute something in background

### ISSUE THREAD

**Issue by GoldsteinE** [ivanceras/sauron#30]
I want to run some code / send message periodically, but I can't find a way to do this. `Cmd::new()` executes everything in the same thread, so I can't just write a loop, and `set_interval` from web-sys requires function to be static, so it's impossible to send message.

How can I achieve this?

**Comment by ivanceras** [comment]
This can be done with the use of `update` function and return a `Cmd` at the end. It will execute again in the next dom update.
This is a [code in futuristic-ui](https://github.com/ivanceras/sauron/blob/e27c30bc2296a4c139adcb11bdd8a88f61b33f8f/examples/futuristic-ui/src/animate_list.rs) where the animation is called periodically until it a condition to stop is met.
