### ISSUE TITLE
JSX similar Syntax ?

### ISSUE THREAD

**Issue by zmlzm** [ivanceras/sauron#4]
This project is nice, Besides Syntax.
Do you have a plan for a new  Syntax (like JSX) ?

**Comment by ivanceras** [comment]
@zmlzm thanks for your interest in the project, however I don't have any plant to support JSX syntax.
There are other projects that supports JSX syntax such as https://github.com/DenisKolodin/yew 

I do plan on putting up online tools to convert html to sauron syntax, in similar fashion with https://mbylstra.github.io/html-to-elm/

**Comment by zmlzm** [comment]
thank you for the explanation，but I think this will be a pain point for people to choose this project.
