### ISSUE TITLE
Correctly set value of HtmlOptionElement

### ISSUE THREAD

**Issue by gbj** [ivanceras/sauron#48]
At the moment, `<option value="...">` does not work as I'd expect. (Sometimes it accidentally works correctly, because when there is no value field set, the browser defaults to using the `innerText` of the `option`.)

The [value fields in the `custom-elements-macro-syntax` example](https://github.com/ivanceras/sauron/blob/39241460a7313f30f714ec5d00b6e12853ba91ba/examples/custom-elements-macro-syntax/src/lib.rs#L35), for example, are actually doing nothing; the values end up being correct because the text content of the `option` is identical with them, but if you change those texts (for example to "Serbian," "English (UK)" and "English (US)" you'll notice that those new values are used as the `value`, and the `value` you give is ignored.

I think you already have this as a to-do (per your comment [here](https://github.com/ivanceras/sauron/blob/39241460a7313f30f714ec5d00b6e12853ba91ba/crates/sauron-core/src/dom/created_node.rs#L467)). There's an [easy fix](https://github.com/gbj/sauron/commit/dcabf6a8e06ba8e12afbc54b04b22370a95c1a13) for `HtmlOptionElement`, but perhaps you'd want to add all the other elements listed there at the same time, and/or a fallback to something like `else { element.set_attribute("value", value); }`?

**Comment by ivanceras** [comment]
Hi @gbj please make a PR even if it the code change is very little. I'm currently working on some other projects, so it would be easier for me to just review and merge PRs.
