### ISSUE TITLE
Closures attached to similar nodes misbehave

### ISSUE THREAD

**Issue by cryslith** [ivanceras/sauron#63]
Related to #3, for performance reasons sauron will not recreate a node when it determines via diffing that it can update it instead.  In particular it cannot detect whether two closures are equal or not for obvious reasons.  However, this leads to strange behavior where event handlers end up on the wrong nodes since the existing nodes were reused instead of being recreated.  For an example see https://github.com/cryslith/sauron-reorder.  (Use the browser console to see which messages are delivered.)

One way to handle this could be to use a special attribute like the suggested `data-disambiguate` to allow specifying to the node diff algorithm that certain nodes should be recreated when data changes.  That is, if `data-disambiguate` differs between the old version and the new version of a node, then the node must be recreated rather than reused.

**Comment by ivanceras** [comment]
Hello @cryslith , thank you for using sauron. 
You can now use `key` attribute to disambiguate similar nodes like this:

```rust
      button(
        [
          key("red"), // suggested fix
          on_click(|_| Msg::RedClicked),
        ],
        [text!("Red")],
      ),
      button(
        [
          key("blue"), // suggested fix
          on_click(|_| Msg::BlueClicked),
        ],
        [text!("Blue")],
      ),
```
I haven't make an announcement about this one. I'll just include it in the next.

**Comment by cryslith** [comment]
Oh, cool!  Thank you very much for the quick reply, I didn't know about this.
