### ISSUE TITLE
Moving to syn-rsx fork

### ISSUE THREAD

**Issue by vldm** [ivanceras/sauron#77]
Hi, i have found that you use `syn-rsx`, which currently looks unmaintained, so i have created a fork.
https://github.com/stoically/syn-rsx/issues/58

If there is any interest in mooving sauron to `rstml`, i can create a PR.
`rstml` already used in Leptos https://github.com/leptos-rs/leptos/pull/1054

**Comment by vldm** [comment]
Hi. I saw that in newest version you already move to rstml. So i will close this issue.

**Comment by ivanceras** [comment]
Ah yeah, I forgot to get back at this issue. rsthml has some really nice ergonomic improvements
