### ISSUE TITLE
todomvc has inverted completed check input

### ISSUE THREAD

**Issue by schell** [ivanceras/sauron#8]
sauron's todomvc implementation uses a checked completion toggle when the todo is *not* complete and vice versa. 

I found this while writing a new benchmarking suite that confirms items are marked complete. `sauron` is the only one I've found with this inverted. 

BTW apart from this little issue (which has nothing to do with performance) sauron performs really well, good job!

**Comment by ivanceras** [comment]
Thanks for reporting it, I'll take a look at this when I have more time.

**Comment by ivanceras** [comment]
[Fixed](https://github.com/ivanceras/sauron/commit/0d6f8375fa3145d804953175d93aa23572a31be8)
