### ISSUE TITLE
Why Sauron is listed as "outdated" on a web framework comparison page?

### ISSUE THREAD

**Issue by vi** [ivanceras/sauron#9]
https://awesomeopensource.com/project/flosse/rust-web-framework-comparison#outdated-frontend-frameworks

**Comment by ivanceras** [comment]
I'm not sure why either why they put my framework as outdated. 
You can perhaps file an issue there, but it's up to their control.
It could be that this is a one-man project and I don't update very often.

**Comment by tshepang** [comment]
this is now not true
