### ISSUE TITLE
Input box value not correctly cleared&rerendered starting from tag 400ms (including all 0.61.0 onward)

### ISSUE THREAD

**Issue by LuxxxLucy** [ivanceras/sauron#96]
I just tried the TodoMVC example, so in the hosted version [](https://ivanceras.github.io/todomvc/) when I hit enter, the input box would be clear because in `app.rs` the value field is reset to a empty string.
![image](https://github.com/ivanceras/sauron/assets/19356905/c98b611b-68f5-473e-b6bc-db1a757fcc55)
and then I hit enter, the input box is cleared.
![image](https://github.com/ivanceras/sauron/assets/19356905/e55cdd53-7880-4a3c-82c9-bc8b431a30f6)

But in the master branch this is broken,  the input box still displayed the previous value.  I checked this manullay by iterating on the tags,  the input box woulld be cleared in tag 0.60.6, and will not be cleared in tag  400ms. So should be some commit or changes in tag 400ms that breaks it.

**Comment by LuxxxLucy** [comment]
Update: after git bisect over the commits found that commit `4d0c1be5` breaks it. Before it the inbox should be cleared if the value is reset to empty, after this commit it will not be updated.

**Comment by ivanceras** [comment]
@LuxxxLucy for reporting, i put the explicit setting of value behind a feature flag `#[cfg(feature = "ensure-attr-set")]`, for benchmarking different strategy, but I forgot to enable defaults. This should be fixed now in the next commits.
